on:
  push:
    branches:
      - main
      - master
    paths-ignore:
      - "Meta**"
      - "data-raw**"
      - "docs**"
      - "inst**"
      - "man**"
      - "memcheck**"
      - "tests**"
      - "vignettes**"
      - "**.git"
      - "**.json"
      - "**.md"
      - "**.yml"
      - "!**revdep.yml"
      - "**.R[dD]ata"
      - "**.Rpro*"
  pull_request:
    branches:
      - main
      - master
    paths-ignore:
      - "Meta**"
      - "memcheck**"
      - "data-raw**"
      - "docs**"
      - "inst**"
      - "man**"
      - "tests**"
      - "vignettes**"
      - "**.git"
      - "**.json"
      - "**.md"
      - "**.yml"
      - "!**revdep.yml"
      - "**.R[dD]ata"
      - "**.Rpro*"

name: revdep-check

jobs:
  mem-check:
    runs-on: ubuntu-latest

    name: revdepcheck

    strategy:
      fail-fast: false
      matrix:
        config:
          - {deps: '"Suggests"'}
          - {deps: '"Imports"'}

    env:
      _R_CHECK_CRAN_INCOMING_: true # Seemingly not set by --as-cran
      _R_CHECK_FORCE_SUGGESTS_: false # CRAN settings
      R_COMPILE_AND_INSTALL_PACKAGES: 'never'
      _R_CHECK_THINGS_IN_CHECK_DIR_: false
      R_REMOTES_STANDALONE: true
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: ${{ matrix.config.rspm }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: ms609/actions/revdepcheck@main
        with:
          deps: ${{ matrix.config.deps }}
